import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  IsBoolean,
  IsInt,
  IsNumber,
  IsOptional,
  IsIn,
  IsPositive,
  Min,
  MaxLength,
  MinLength,
} from 'class-validator';
import { Type } from 'class-transformer';
import { FraudAlertSeverity } from '@bienbon/shared-types';

const ACTOR_TYPES = ['CONSUMER', 'PARTNER'] as const;
const OPERATORS = ['GT', 'GTE', 'LT', 'LTE', 'EQ'] as const;
const ACTIONS = ['FLAG', 'BLOCK', 'SUSPEND'] as const;
const SEVERITIES = Object.values(FraudAlertSeverity) as string[];

/**
 * DTO for creating a new fraud detection rule.
 */
export class CreateFraudRuleDto {
  @ApiProperty({
    description: 'Unique slug identifier for the rule',
    example: 'consumer-no-show-3d',
  })
  @IsString()
  @MinLength(3)
  @MaxLength(100)
  slug!: string;

  @ApiProperty({
    description: 'Rule name in French',
    example: 'Absence répétée (consommateur)',
  })
  @IsString()
  @MinLength(1)
  @MaxLength(200)
  nameFr!: string;

  @ApiPropertyOptional({
    description: 'Rule name in English',
    example: 'Repeated no-show (consumer)',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  nameEn?: string;

  @ApiPropertyOptional({
    description: 'Rule description in French',
  })
  @IsOptional()
  @IsString()
  descriptionFr?: string;

  @ApiPropertyOptional({
    description: 'Rule description in English',
  })
  @IsOptional()
  @IsString()
  descriptionEn?: string;

  @ApiProperty({
    description: 'Actor type the rule applies to',
    enum: ACTOR_TYPES,
    example: 'CONSUMER',
  })
  @IsIn(ACTOR_TYPES)
  actorType!: 'CONSUMER' | 'PARTNER';

  @ApiProperty({
    description: 'Metric being measured (e.g. no_shows, cancellations, claims)',
    example: 'no_shows',
  })
  @IsString()
  @MinLength(1)
  @MaxLength(100)
  metric!: string;

  @ApiProperty({
    description: 'Comparison operator',
    enum: OPERATORS,
    example: 'GT',
  })
  @IsIn(OPERATORS)
  operator!: 'GT' | 'GTE' | 'LT' | 'LTE' | 'EQ';

  @ApiProperty({
    description: 'Threshold value for the metric',
    example: 3,
  })
  @IsNumber()
  @IsPositive()
  @Type(() => Number)
  threshold!: number;

  @ApiPropertyOptional({
    description: 'Time window in days',
    example: 30,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Type(() => Number)
  windowDays?: number;

  @ApiPropertyOptional({
    description: 'Time window in hours',
    example: 24,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Type(() => Number)
  windowHours?: number;

  @ApiPropertyOptional({
    description: 'Time window in minutes',
    example: 60,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Type(() => Number)
  windowMinutes?: number;

  @ApiPropertyOptional({
    description: 'Minimum number of events required to trigger the rule',
    default: 1,
    example: 3,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Type(() => Number)
  minSampleSize?: number;

  @ApiProperty({
    description: 'Action to take when rule is triggered',
    enum: ACTIONS,
    example: 'FLAG',
  })
  @IsIn(ACTIONS)
  action!: 'FLAG' | 'BLOCK' | 'SUSPEND';

  @ApiProperty({
    description: 'Severity of alerts generated by this rule',
    enum: FraudAlertSeverity,
    example: FraudAlertSeverity.MEDIUM,
  })
  @IsIn(SEVERITIES)
  severity!: FraudAlertSeverity;

  @ApiPropertyOptional({
    description: 'Whether the rule is active',
    default: true,
  })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  @ApiPropertyOptional({
    description: 'Cooldown period in hours before the rule can trigger again for the same actor',
    default: 24,
    example: 24,
  })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Type(() => Number)
  cooldownHours?: number;
}
